/**
 * Browsers auto-request `/favicon.ico` for any document root, even
 * when a <link rel="icon"> points elsewhere. The real icon lives at
 * /icon (generated by app/icon.tsx). This handler answers the
 * legacy probe with 204 No Content so we don't leave a 404 in the
 * access log.
 */

export function GET(): Response {
  return new Response(null, {
    status: 204,
    headers: {
      "Cache-Control": "public, max-age=86400, immutable",
    },
  });
}
