/**
 * lib/validators/rr-types/tlsa.ts
 *
 * TLSA (DANE for TLS) content - RFC 6698 + RFC 7218:
 *   `<usage> <selector> <matching-type> <cert-data>`
 *
 *   - usage         : uint8 (0–3) - RFC 7218 mnemonics in IANA registry.
 *                     0 = PKIX-TA (CA constraint)
 *                     1 = PKIX-EE (service certificate constraint)
 *                     2 = DANE-TA (trust anchor assertion)
 *                     3 = DANE-EE (domain-issued certificate, the most
 *                                  commonly-deployed value).
 *   - selector      : uint8 (0–1).
 *                     0 = Cert (full certificate)
 *                     1 = SPKI (SubjectPublicKeyInfo)
 *   - matching-type : uint8 (0–2).
 *                     0 = Full (no hash; cert-data is the full thing
 *                              in hex - variable, often large)
 *                     1 = SHA-256 (64 hex chars)
 *                     2 = SHA-512 (128 hex chars)
 *   - cert-data     : hex (case-insensitive). For matching-type 1/2 the
 *                     length is fixed; for matching-type 0 anything
 *                     plausibly-hex is accepted with a warning that
 *                     short values are likely wrong.
 *
 * Common operator workflow: TLSA records are usually generated by tools
 * like `openssl` + `xxd` or by ACME clients. Manual entry is rare but
 * happens for trust-anchor pinning. This validator catches the
 * paste mistakes - wrong matching-type/length pair, leftover
 * formatting marks, mistyped usage code.
 */

import type { RRTypeValidator, RRValidationIssue } from "./types";

const USAGE_NAMES: Record<number, string> = {
  0: "PKIX-TA",
  1: "PKIX-EE",
  2: "DANE-TA",
  3: "DANE-EE",
};

const SELECTOR_NAMES: Record<number, string> = {
  0: "Cert",
  1: "SPKI",
};

const MATCHING_TYPE: Record<number, { name: string; length: number | "variable" }> = {
  0: { name: "Full", length: "variable" },
  1: { name: "SHA-256", length: 64 },
  2: { name: "SHA-512", length: 128 },
};

export const tlsaValidator: RRTypeValidator = {
  type: "TLSA",
  label: "TLSA (DANE for TLS)",
  description:
    "usage selector matching-type cert-data (RFC 6698). Typical: `3 1 1 <sha256-of-spki>` for DANE-EE.",
  placeholder: "3 1 1 a1b2c3...64hex...",
  rfc: "RFC 6698 + RFC 7218",
  validate(content: string) {
    const issues: RRValidationIssue[] = [];
    const trimmed = content.trim();

    // cert-data can be very long for matching-type 0 (full cert); allow
    // whitespace inside it and strip later. Match first three numeric
    // tokens then take the rest as cert-data material.
    const match = /^(\S+)\s+(\S+)\s+(\S+)\s+(.+)$/s.exec(trimmed);
    if (!match) {
      return {
        issues: [
          {
            level: "error",
            message:
              "TLSA content needs four parts: `<usage> <selector> <matching-type> <cert-data>` (RFC 6698).",
          },
        ],
        normalized: trimmed,
      };
    }
    const [, usageStr, selectorStr, matchingStr, rawCert] = match as unknown as [
      string,
      string,
      string,
      string,
      string,
    ];

    // usage: uint8, but only 0–3 are defined.
    let usage: number | null = null;
    if (!/^\d+$/.test(usageStr)) {
      issues.push({
        level: "error",
        message: `Usage "${usageStr}" is not a non-negative integer.`,
      });
    } else {
      usage = Number(usageStr);
      if (usage < 0 || usage > 255) {
        issues.push({
          level: "error",
          message: "Usage must be 0–255 (8-bit unsigned).",
        });
        usage = null;
      } else if (!(usage in USAGE_NAMES)) {
        issues.push({
          level: "warning",
          message: `Usage ${usage} is not defined in RFC 7218 (0=PKIX-TA, 1=PKIX-EE, 2=DANE-TA, 3=DANE-EE).`,
        });
      }
    }

    // selector: uint8, 0 or 1 defined.
    let selector: number | null = null;
    if (!/^\d+$/.test(selectorStr)) {
      issues.push({
        level: "error",
        message: `Selector "${selectorStr}" is not a non-negative integer.`,
      });
    } else {
      selector = Number(selectorStr);
      if (selector < 0 || selector > 255) {
        issues.push({
          level: "error",
          message: "Selector must be 0–255 (8-bit unsigned).",
        });
        selector = null;
      } else if (!(selector in SELECTOR_NAMES)) {
        issues.push({
          level: "warning",
          message: `Selector ${selector} is not defined in RFC 7218 (0=Cert, 1=SPKI).`,
        });
      }
    }

    // matching-type: uint8, 0/1/2 defined.
    let matchingType: number | null = null;
    if (!/^\d+$/.test(matchingStr)) {
      issues.push({
        level: "error",
        message: `Matching-type "${matchingStr}" is not a non-negative integer.`,
      });
    } else {
      matchingType = Number(matchingStr);
      if (matchingType < 0 || matchingType > 255) {
        issues.push({
          level: "error",
          message: "Matching-type must be 0–255 (8-bit unsigned).",
        });
        matchingType = null;
      }
    }

    // cert-data: hex, length per matching-type.
    const certCompact = rawCert.replace(/\s+/g, "").toLowerCase();
    if (!/^[0-9a-f]*$/.test(certCompact)) {
      issues.push({
        level: "error",
        message: "Cert-data must be hex (0–9, A–F). Strip non-hex characters before saving.",
      });
    } else if (certCompact.length === 0) {
      issues.push({
        level: "error",
        message: "Cert-data is empty.",
      });
    } else if (matchingType !== null) {
      const spec = MATCHING_TYPE[matchingType];
      if (spec) {
        if (typeof spec.length === "number") {
          if (certCompact.length !== spec.length) {
            issues.push({
              level: "error",
              message: `Matching-type ${matchingType} (${spec.name}) requires ${spec.length} hex characters; got ${certCompact.length}.`,
            });
          }
        } else {
          // Variable-length (matching-type 0, full cert). Sanity-warn
          // when the hex is suspiciously short - a real cert in hex
          // is hundreds of chars minimum.
          if (certCompact.length < 200) {
            issues.push({
              level: "warning",
              message:
                "Matching-type 0 (Full) usually requires hundreds of hex characters (a whole cert or SPKI). The short value here might be wrong.",
            });
          }
        }
      } else {
        issues.push({
          level: "warning",
          message: `Matching-type ${matchingType} is not in {0,1,2} - RFC 6698 defines no others.`,
        });
      }
    }

    const normalizedParts: string[] = [
      usage !== null ? String(usage) : usageStr,
      selector !== null ? String(selector) : selectorStr,
      matchingType !== null ? String(matchingType) : matchingStr,
      certCompact || rawCert.trim(),
    ];

    return {
      issues,
      normalized: normalizedParts.join(" "),
    };
  },
};
