/**
 * lib/db/schema/_helpers.ts
 *
 * Shared column helpers. Pulled out so every table file can use the same
 * timestamp + UUID-PK conventions without copy-paste.
 *
 * Conventions:
 *  - Primary keys: uuid, generated by Postgres' `gen_random_uuid()` (pgcrypto
 *    extension; available by default since Postgres 13).
 *  - Timestamps: `timestamptz` always. Never `timestamp` (which loses TZ data
 *    in transit). `created_at` defaults to `now()`; `updated_at` is updated by
 *    application code, not by DB triggers, so it stays observable.
 */

import { sql } from "drizzle-orm";
import { timestamp, uuid } from "drizzle-orm/pg-core";

/** UUID primary key generated by Postgres. */
export const pk = () =>
  uuid("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`);

/** Standard created_at / updated_at columns. */
export const timestamps = () => ({
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
