/**
 * lib/db/schema/saml-providers.ts
 *
 * DB-backed SAML 2.0 service-provider configurations (ADR-0021). Each row is
 * one IdP relationship: AD FS, Authentik SAML, Keycloak SAML, etc. The slug
 * is the operator-facing handle used in the ACS / metadata / SLO route
 * segments (`/api/auth/saml/<slug>/{login,acs,metadata,slo}`); it is also
 * reserved in `auth_provider_slugs` for cross-type uniqueness with OIDC and
 * LDAP.
 *
 * Encrypted PEM material:
 *   - `sp_signing_key_encrypted` — the SP's private signing key, used to
 *     sign outbound AuthnRequest / LogoutRequest. Mandatory; generated by
 *     the create route via `lib/crypto/encryption.ts#encrypt`.
 *   - `sp_encryption_key_encrypted` — optional. When set, the IdP may
 *     EncryptedAssertion-encrypt assertions to the matching cert and we
 *     decrypt server-side. Operators typically reuse the signing keypair
 *     for both unless their IdP requires separate use.
 *
 * IdP material (`idp_signing_cert`) is the public cert the IdP uses to sign
 * Responses; we use it to verify the inbound assertion. Stored plain (it's
 * a public cert).
 */

import { boolean, jsonb, pgTable, text, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { users } from "./users";
import { pk, timestamps } from "./_helpers";

export const samlProviders = pgTable(
  "saml_providers",
  {
    id: pk(),

    /**
     * URL-safe slug — used as the `<slug>` path segment in
     * `/api/auth/saml/<slug>/...`. Cannot be changed once created (would
     * break in-flight sign-in attempts).
     */
    slug: text("slug").notNull(),

    /** Human display name on the login button. */
    name: text("name").notNull(),

    /** IdP entityID (Issuer). Used to verify the inbound Response's Issuer. */
    idpEntityId: text("idp_entity_id").notNull(),
    /** IdP SSO endpoint — where we redirect for the AuthnRequest. */
    idpSsoUrl: text("idp_sso_url").notNull(),
    /** IdP single-logout endpoint. Optional — when null, SLO falls back to
     *  local cookie-clear with no IdP round-trip. */
    idpSloUrl: text("idp_slo_url"),
    /** Public PEM cert the IdP signs Responses with. */
    idpSigningCert: text("idp_signing_cert").notNull(),

    /** Encrypted SP signing private key (PEM). AES-256-GCM envelope. */
    spSigningKeyEncrypted: text("sp_signing_key_encrypted").notNull(),
    /** Public SP signing cert (PEM). Published in metadata. */
    spSigningCert: text("sp_signing_cert").notNull(),

    /** Optional encryption private key (PEM, encrypted). When null, the SP
     *  doesn't advertise an encryption cert and the IdP MUST send plaintext
     *  assertions. */
    spEncryptionKeyEncrypted: text("sp_encryption_key_encrypted"),
    /** Optional encryption public cert (PEM). Published in metadata when set. */
    spEncryptionCert: text("sp_encryption_cert"),

    /** When true, the SP rejects unsigned Responses. Defaults true per ADR-0021. */
    requireSignedResponse: boolean("require_signed_response").notNull().default(true),
    /** When true, the SP requires the IdP to encrypt assertions to its
     *  encryption cert. Defaults false. */
    requireEncryptedAssertion: boolean("require_encrypted_assertion").notNull().default(false),

    /** XML-DSig signature algorithm — `sha1` (legacy), `sha256` (default), or
     *  `sha512`. Stored as a short string so the validator can keep its
     *  vocabulary in one place. */
    signatureAlgorithm: text("signature_algorithm").notNull().default("sha256"),

    /** NameID format the SP requests in AuthnRequest. */
    nameIdFormat: text("name_id_format")
      .notNull()
      .default("urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"),

    /** Attribute name carrying the user's email. Defaults to "email";
     *  ADFS/Azure typically set the friendly form on `mail` or the urn-oid form. */
    claimEmail: text("claim_email").notNull().default("email"),
    /** Attribute name carrying the user's display name. */
    claimName: text("claim_name").notNull().default("name"),
    /** Attribute name carrying the user's group memberships (string array or
     *  delimited string). */
    claimGroups: text("claim_groups").notNull().default("groups"),

    /** Soft-disable. Disabled providers stay in the DB for audit history. */
    enabled: boolean("enabled").notNull().default(true),

    /** Per-provider email-domain override (same three-state semantics as OIDC).
     *  Null = no override; empty array = "no restriction"; non-empty = list. */
    allowedEmailDomains: jsonb("allowed_email_domains").$type<string[]>(),

    /** Group → role-assignment mappings (same shape as OIDC). Resolved at
     *  sign-in time; admin-issued assignments untouched. */
    groupMappings: jsonb("group_mappings").$type<SamlGroupMapping[]>(),

    /** Who added it. NULL for provisioning-seeded rows. */
    createdBy: uuid("created_by").references(() => users.id, {
      onDelete: "set null",
    }),

    ...timestamps(),
  },
  (t) => ({
    slugIdx: uniqueIndex("saml_providers_slug_idx").on(t.slug),
  }),
);

export type SamlProvider = typeof samlProviders.$inferSelect;
export type NewSamlProvider = typeof samlProviders.$inferInsert;

/**
 * One group → role-assignment rule for a SAML provider. Identical shape to
 * the neutral `GroupMapping` in `lib/auth/providers/group-sync-pure.ts`;
 * the compute path (`computeGroupSync`) is protocol-agnostic.
 */
export interface SamlGroupMapping {
  /** Exact group value to match in the user's group attribute. Case-sensitive. */
  group: string;
  /** Role slug to assign — system or custom; resolved at sign-in time. */
  roleSlug: string;
  scopeType: "global" | "team" | "zone" | "server";
  /** Scope target. Null when scopeType=global; slug or zone-name otherwise. */
  scopeId: string | null;
}
